# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: ski-station-config
#   namespace: ski-station
# data:
#   application.yml: |
#     server:
#       servlet:
#         context-path: /api
#       port: 8089
#     spring:
#       application:
#         name: ski-station-api
#       datasource:
#         url: jdbc:mysql://mysql-service:3306/stationSki?createDatabaseIfNotExist=true
#         username: springuser
#         password: springpassword
#       jpa:
#         hibernate:
#           ddl-auto: update
#         show-sql: true
#         properties:
#           hibernate:
#             dialect: org.hibernate.dialect.MySQLDialect
#     management:
#       endpoints:
#         web:
#           exposure:
#             include: health,info,prometheus,metrics
#       endpoint:
#         health:
#           show-details: always
#       metrics:
#         export:
#           prometheus:
#             enabled: true
#     logging:
#       level:
#         tn.esprit.spring: INFO
#         root: INFO
#       pattern:
#         console: "=%d{yyyy-MM-dd HH:mm:ss} - %-5level - %logger{45} - %msg %n"