# Create namespace manifests
apiVersion: v1
kind: Namespace
metadata:
  name: ski-station
  labels:
    name: ski-station
    app.kubernetes.io/name: ski-station
    app.kubernetes.io/component: backend
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/component: observability